# Generated by Django 5.1.6 on 2025-02-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brp_kennisgevingen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newresident",
            name="birthdate",
            field=models.DateTimeField(null=True),
        ),
    ]
