# Generated by Django 5.2.3 on 2025-07-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brp_kennisgevingen", "0002_newresident_birthdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="end_date",
            field=models.DateField(null=True),
        ),
    ]
