# Generated by Django 5.2.3 on 2025-09-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brp_kennisgevingen", "0004_subscription_created_at_subscription_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newresident",
            name="birthdate",
            field=models.DateField(null=True),
        ),
    ]
