# Generated by Django 5.2.5 on 2025-10-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brp_kennisgevingen", "0005_alter_newresident_birthdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="BSNUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("application_id", models.CharField(max_length=255)),
                ("old_bsn", models.CharField(max_length=9, unique=True)),
                ("new_bsn", models.CharField(max_length=9, unique=True)),
                ("inserted_at", models.DateTimeField(null=True)),
            ],
        ),
    ]
