# Generated by Django 5.2.7 on 2025-11-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brp_kennisgevingen", "0006_bsnchange"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bsnchange",
            name="new_bsn",
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name="bsnchange",
            name="old_bsn",
            field=models.CharField(max_length=9),
        ),
    ]
