# Generated by Django 5.2.7 on 2025-12-09 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brp_kennisgevingen", "0007_alter_bsnchange_new_bsn_alter_bsnchange_old_bsn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bsnchange",
            name="application_id",
        ),
    ]
