# Generated by Django 5.2.3 on 2026-01-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brp_kennisgevingen", "0008_remove_bsnchange_application_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bsnchange",
            name="valid_from",
            field=models.DateField(),
        ),
    ]
