# Generated by Django 5.2.11 on 2026-03-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brp_kennisgevingen", "0009_alter_bsnchange_valid_from"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bsnchange",
            name="id",
        ),
        migrations.AlterField(
            model_name="bsnchange",
            name="old_bsn",
            field=models.CharField(max_length=9, primary_key=True, serialize=False, unique=True),
        ),
    ]
