name: Run Pytest
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
    - features/**
  pull_request:
    branches:
    - main
    - master

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    # Run against multiple Postgres versions, while we migrate the db.
    strategy:
      fail-fast: false
      matrix:
        postgres-version:
          - 14
          - 17
    env:
      INITIALIZE_DB: false
      POSTGRES_VERSION: ${{ matrix.postgres-version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker compose -f "docker-compose.yml" up -d --build

    - name: Run tests
      run: docker compose exec -T web pytest -v --ds=tests.settings --show-capture=no

    - name: Stop containers
      if: always()
      run: docker compose -f "docker-compose.yml" down
